import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Three sidebars over ONE content root (`../docs`).
 *
 * A single plugin instance is deliberate: this tree cross-links heavily between the guide, the
 * reference pages and the design records, and Docusaurus only resolves relative `.md` links WITHIN an
 * instance. Splitting into four instances the way larger projects do would break those links on the
 * first build. See `docs/architecture/docs-site.md`.
 *
 * `guide` and `internals` are autogenerated from the directory, so a new file cannot go missing from
 * the navigation. The reference sidebar is hand-ordered because the root docs have no directory to
 * imply an order.
 */
const sidebars: SidebarsConfig = {
  guideSidebar: [{ type: "autogenerated", dirName: "guide" }],

  referenceSidebar: [
    { type: "doc", id: "README", label: "All documents" },
    {
      type: "category",
      label: "Surfaces",
      collapsed: false,
      items: ["api", "mcp", "web", "everdict-otel"],
    },
    {
      type: "category",
      label: "Eval entities",
      collapsed: false,
      items: [
        "registry",
        "datasets",
        "judges",
        "models",
        "runtimes",
        "scorecards",
        "suites",
        "command-harness",
        "service-harness",
      ],
    },
    {
      type: "category",
      label: "Execution",
      collapsed: false,
      items: ["execution-backends", "orchestration"],
    },
    {
      type: "category",
      label: "Tenancy & auth",
      collapsed: false,
      items: ["auth", "tenancy", "secrets", "sandbox-auth"],
    },
    {
      type: "category",
      label: "Verdicts & billing",
      collapsed: false,
      items: ["trust-certification", "tracker", "usage-metering"],
    },
    {
      type: "category",
      label: "Operations",
      collapsed: false,
      items: [
        "dev",
        "runbooks/corporate-proxy",
        "runbooks/github-self-hosted-runner",
        {
          type: "category",
          label: "Database migrations",
          items: [{ type: "autogenerated", dirName: "migration" }],
        },
      ],
    },
  ],

  internalsSidebar: [{ type: "autogenerated", dirName: "architecture" }],
};

export default sidebars;
