// Bundle the STANDALONE runner entry into one self-contained CJS file — the input to the Node SEA build that produces
// the distributable `everdict-runner` binary (release CI). Only `runner-standalone.ts` is bundled (NOT main.ts): it
// excludes @everdict/orchestrator, so Temporal's native Rust bindings never enter the graph and esbuild can inline
// everything (@everdict/self-hosted-runner + @everdict/job-runner, the same graph the desktop already bundles).
// The gate (turbo build) stays tsc (dist/) — this script is for `pnpm bundle` / release packaging only.
// Design: docs/architecture/runner-distribution.md.
//
// INVARIANT: this resolves each @everdict/* workspace dep through its package `exports` → its built `dist/`, so a stale
// dist gets baked into the binary verbatim (e.g. an out-of-date @everdict/contracts Zod enum → the runner rejects a
// newer leased job with `invalid_enum_value`). The `package:runner` script therefore runs `turbo run build --filter`
// FIRST so every upstream dist is fresh before we bundle (release CI does the same); never run this on an unbuilt tree.
import { build } from "esbuild";

await build({
  entryPoints: ["src/runner-standalone.ts"],
  bundle: true,
  platform: "node",
  format: "cjs", // CJS — Node SEA loads the blob as CommonJS (the stable single-executable path).
  target: "node22",
  outfile: "bundle/everdict-runner.cjs",
  // node built-ins stay external (provided by the node runtime the SEA is injected into).
  banner: {
    js: "#!/usr/bin/env node\n// everdict-runner — self-contained self-hosted runner (generated by esbuild; do not edit).",
  },
});
