import { execFile } from "node:child_process";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import { BadRequestError, UpstreamError } from "@everdict/contracts";
import { parseImageRef } from "@everdict/domain";

const pexecFile = promisify(execFile);

// everdict image bake — wrap a BYO eval image with the everdict in-job agent so it runs on MANAGED
// runtimes (nomad/k8s), where the case.image becomes the orchestrator task image and must boot the
// agent itself (EVERDICT_AGENT_JOB contract). Self-hosted runners containerize via DockerDriver and
// don't need this. Design: docs/architecture/managed-case-image.md

export const DEFAULT_AGENT_IMAGE = "everdict-agent:slim";

// The generated multi-stage Dockerfile — copies the agent dist + node binary from the agent image into
// the base image and makes the agent the entrypoint. libstdc++6 is node's one non-libc shared-library
// dependency that slim (python/debian-slim style) bases commonly lack; ca-certificates for the agent's
// outbound TLS (judge/model calls). Both are no-ops when already present.
export function bakeDockerfile(baseRef: string, agentRef: string = DEFAULT_AGENT_IMAGE): string {
  return [
    `# Generated by \`everdict image bake\` — ${baseRef} + the everdict in-job agent (${agentRef}).`,
    "# Managed runtimes (nomad/k8s) run the case.image AS the task image, so the image must boot the",
    "# agent itself (EVERDICT_AGENT_JOB env contract). The agent then runs the harness command in-place.",
    `FROM ${agentRef} AS agent`,
    "",
    `FROM ${baseRef}`,
    "COPY --from=agent /usr/local/bin/node /usr/local/bin/node",
    "COPY --from=agent /app /everdict-agent",
    "RUN apt-get update && apt-get install -y --no-install-recommends libstdc++6 ca-certificates \\",
    "  && rm -rf /var/lib/apt/lists/* \\",
    "  && node --version",
    'ENTRYPOINT ["node", "/everdict-agent/dist/main.js"]',
    "CMD []",
    "",
  ].join("\n");
}

// Default target ref: append "-agent" to the base tag (browseruse-eval:0.13.3 → browseruse-eval:0.13.3-agent).
export function bakeTargetRef(baseRef: string): string {
  const parsed = parseImageRef(baseRef);
  const tag = parsed.tag ?? "latest";
  const host = parsed.host ? `${parsed.host}/` : "";
  return `${host}${parsed.path}:${tag}-agent`;
}

interface ImageBakeIo {
  log: (message: string) => void;
  docker: (args: string[]) => Promise<void>;
}

const defaultDocker = async (args: string[]): Promise<void> => {
  try {
    await pexecFile("docker", args, { maxBuffer: 16 * 1024 * 1024 });
  } catch (e) {
    const stderr = e instanceof Error && "stderr" in e ? String((e as { stderr?: unknown }).stderr ?? "") : "";
    throw new UpstreamError(
      "UPSTREAM_ERROR",
      { args: args.join(" ") },
      `docker ${args[0]} failed: ${stderr || String(e)}`,
    );
  }
};

// Write the generated Dockerfile to a temp dir and docker-build the baked tag. Returns the baked ref.
export async function bakeImage(
  baseRef: string,
  opts: { agentImage?: string; tag?: string; io?: ImageBakeIo } = {},
): Promise<string> {
  const io: ImageBakeIo = opts.io ?? { log: (m) => console.error(m), docker: defaultDocker };
  const agentRef = opts.agentImage ?? DEFAULT_AGENT_IMAGE;
  const target = opts.tag ?? bakeTargetRef(baseRef);
  const dir = await mkdtemp(join(tmpdir(), "everdict-bake-"));
  try {
    await writeFile(join(dir, "Dockerfile"), bakeDockerfile(baseRef, agentRef));
    io.log(`▶ docker build -t ${target} (${baseRef} + agent ${agentRef})`);
    await io.docker(["build", "-t", target, dir]);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
  return target;
}

// everdict image bake <base-ref> [--agent-image <ref>] [--tag <target-ref>]
export async function imageBakeCommand(baseRef: string | undefined, flags: Map<string, string>): Promise<void> {
  if (!baseRef)
    throw new BadRequestError(
      "BAD_REQUEST",
      undefined,
      "a base image reference to bake is required — everdict image bake <ref>",
    );
  const target = await bakeImage(baseRef, { agentImage: flags.get("agent-image"), tag: flags.get("tag") });
  console.error("✓ Baked — pin this reference for MANAGED runtimes (push it if the runtime pulls from a registry):");
  console.log(target);
}
